on:
  issues:
    type: [opened]

name: Handle Issues

jobs:
  review_new_issue_job:
    runs-on: ubuntu-latest
    name: A job to review a new issue for fulfilled requirements
    steps:
      - uses: actions/checkout@master
      - uses: ./review-new-issue-action
        name: Review New Issue Step
        id: review
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
