on:
  issues:
    type: [opened]

jobs:
  review_new_issue_job:
    runs-on: ubuntu-latest
    name: A job to review a new issue for fulfilled requirements
    steps:
      - uses: actions/checkout@master
      - uses: ./review-new-issue-action@v1
        name: Review New Issue Step
        id: review

