on:
  issues:
    type: [opened]

jobs:
  review_new_issue_job:
    runs-on: ubuntu-latest
    name: A job to review a new issue for fulfilled requirements
    steps:
      - name: Review New Issue Step
        id: review
        uses: actions/review-new-issue-action@v1

